version: '3'

networks:
  frontend_net:
    driver: bridge

services:
  frontend:
    build: ./frontend
    container_name: frontend
    command: npm start
    volumes:
      - ./frontend/src:/home/frontend/src
    networks:
      - frontend_net
    ports:
      - "3000:3000"
