version: '3'

networks:
  default:
    external:
      name: profile_profile_net

services:
  frontend:
    build: ./frontend
    container_name: frontend
    command: npm start
    volumes:
      - ./frontend/src:/home/frontend/src
    networks:
      - default
    ports:
      - "3000:3000"
